spring:
  profiles:
    active: @spring.profiles.active@
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oa12o3l02a4QVtNC357
            client-secret: PpoQleNSmH0A70cWzCUnh8MXWiEoPmgrrV00Eu5J
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: https://dev-868143.okta.com/oauth2/default